name: lttimer
description: A new Flutter project.
publish_to: 'none'

version: 0.1.7+9

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  # audioplayers: ^4.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  go_router: ^9.0.0
  google_fonts: ^4.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  just_audio: ^0.9.34
  lottie: ^2.4.0
  package_info_plus: ^4.0.2
  riverpod_annotation: ^2.1.1
  settings_ui: ^2.0.2
  slang: ^3.19.0
  slang_flutter: ^3.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.3
  build_runner: ^2.4.6
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/clapping.json
    - assets/party_popper.json
    - assets/tada.json
    - assets/clapping.mp3
    - assets/bell.mp3
    - assets/fonts/zentaku_gothic_new/
    - assets/fonts/roboto_mono/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/lttimer_ios.png"
  adaptive_icon_foreground: "assets/icon/lttimer_android.png"
  adaptive_icon_background: "#FF9800"
  web:
    generate: true
    image_path: "assets/icon/lttimer_ios.png"
  macos:
    generate: true
    image_path: "assets/icon/lttimer_ios.png"
